#!/bin/bash
source .env

running_containers=$(sudo docker ps -q)
if [ -n "$running_containers" ]; then
    echo "Stopping all running Docker containers"
    sudo docker stop $running_containers
    sudo docker remove $running_containers
fi

sudo remove acoustic
# Build the Docker image
# sudo docker build --no-cache -t acoustic .
sudo docker build -t acoustic .

# Run the Docker container
sudo docker run -d -p 80:80 \
    -e DB_HOST=$DB_HOST \
    -e DB_NAME=$DB_NAME \
    -e DB_USER=$DB_USER \
    -e DB_PASS=$DB_PASS \
    -e DB_PORT=$DB_PORT \
    -e DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY \
    -e DJANGO_DEBUG=$DJANGO_DEBUG \
    -e DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS \
    --name acoustic acoustic

# Check container logs
echo "Checking the docker has an open port"
lsof -i -P -n | grep LISTEN
# ss -tuln

echo "Checking the docker logs, look for the result of the internal health check"
sleep 10
sudo docker logs acoustic
