#!/bin/bash



# Create a virtual environment
sudo apt-get install default-libmysqlclient-dev 
python3 -m venv ./venv

# Activate the virtual environment
source ./venv/bin/activate
source .env

#django-admin startproject acoustic-calcs

# Install the required packages
pip install -r requirements.txt
pip install -r requirements.dev.txt

cd app
flake8 .


#python manage.py runserver 0.0.0.0:8000
sudo apt install postgresql postgresql-contrib
sudo -i -u postgres
psql
CREATE DATABASE acoustic_calcs;
CREATE USER acoustic WITH PASSWORD '!YouNever74890&';
GRANT ALL PRIVILEGES ON DATABASE acoustic_calcs TO acoustic;
ALTER USER acoustic CREATEDB;
\c acoustic_calcs
GRANT ALL PRIVILEGES ON SCHEMA public TO acoustic;


psql -h acoustic.cx682uusurxl.ap-southeast-2.rds.amazonaws.com -U postgres -W

python manage.py makemigrations
python manage.py migrate
python manage.py createsuperuser

python manage.py runserver 0.0.0.0:8000

PGPASSWORD=FzAydWhDIgUzLrrlqJBq psql -h acoustic.cx682uusurxl.ap-southeast-2.rds.amazonaws.com -U postgres << EOF
CREATE DATABASE acoustic_calcs;
CREATE USER acoustic WITH PASSWORD '!YouNever74890';
GRANT ALL PRIVILEGES ON DATABASE acoustic_calcs TO acoustic;
\c acoustic_calcs
GRANT ALL PRIVILEGES ON SCHEMA public TO acoustic;
EOF

PGPASSWORD=FzAydWhDIgUzLrrlqJBq psql -h acoustic.cx682uusurxl.ap-southeast-2.rds.amazonaws.com -U postgres << EOF
ALTER USER acoustic CREATEDB;
EOF

python manage.py runserver 0.0.0.0:8000