#!/bin/bash

sudo apt install python3 python3-venv

# Create a virtual environment
python3 -m venv venv

# Activate the virtual environment
echo "Run command to Active python enviroment"
echo "source venv/bin/activate"

# Install necessary packages
pip install numpy